cc_library(
    name = "all_libs",
    srcs = glob(["*.c"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "hello",
    srcs = ["hello.c"],
    hdrs = ["include/hello.h"],
    visibility = ["//visibility:public"],
)
