load("//tools/ThrowTheSwitch/Unity:unity.bzl", "unity_test")

unity_test(
    name = "test_logging",
    srcs = ["test_logging.c"],
    #  my_config = ["my_config.yml"],
    deps = [
        "@logging",
    ],
)
