load("//third_party/http/ThrowTheSwitch/Unity:unity.bzl", "unity_test")

unity_test(
    size = "small",
    cexception = False,
    file_name = "test_armstrong_numbers.c",
    deps = [
        "//src:armstrong_numbers",
    ],
)
