load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "example_lib",
    srcs = [
        "src/example_lib.c",
    ],
    hdrs = ["include/example_lib.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)
