# cc_library(
#     name = "CMock",
#     srcs = ["src/cmock.c"],
#     hdrs = [
#         "src/cmock.h",
#         "src/cmock_internals.h",
#     ],
#     copts = ["-DUNITY_INCLUDE_DOUBLE"],
#     includes = ["src"],
#     visibility = ["//visibility:public"],
#     deps = [
#         "@Unity",
#     ],
# )
