cc_library(
    name = "llist",
    srcs = ["llist.c"],
    hdrs = ["llist.h"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "example_llist",
    srcs = ["example_llist.c"],
    deps = ["//lib/llist"],
)
