"""Unit tests for example_lib."""

load("//tools/build:cc_rules.bzl", "c_test")

c_test(
    name = "test_example_lib",
    srcs = [
        "test_example_lib.c",
    ],
    deps = [
        "//lib/example_lib",
    ],
)
