"""Unit tests for example_lib."""

load("//:tools/unity_test.bzl", "unity_test")

unity_test(
    name = "test_example_lib",
    srcs = [
        "test_example_lib.c",
    ],
    deps = [
        "//app/example_lib",
    ],
)
